### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by zxchew2014** [dteskera/wagtailcloudinary#1]

**Comment by dteskera** [comment]
im not working with wagtail anymore, so this could be incompatible with the latest.
give it a shot, if it works fine, if not fork it and adapt.

cheers.

**Comment by bufke** [comment]
Hello, the agency I work with is evaluating using this and updating it. Would you prefer we submit fixes here or just fork it? The wagtail imports no longer work with current wagtail.

**Comment by bufke** [comment]
Here's where I am so far if anyone else is interested

- Wagtail import paths have changed, trivial fix
- Needed to update how urls work in sites.py - another easy one
- Wagtail 2.2 deprecated the js argument in render_modal_workflow. This one is big.

Progress (nothing else but this listing works currently)

![image](https://user-images.githubusercontent.com/739307/51323565-9319ab80-1a36-11e9-831a-bbeca4e470ad.png)

**Comment by bufke** [comment]
Got it working with wagtail 2.4. Code is at https://gitlab.com/thelabnyc/wagtailcloudinary
